spring.application.name=wms

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/spring
spring.datasource.username=admin
spring.datasource.password=123123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# Auth - OAuth
auth.oauth.redirectUri=http://localhost:3000/auth/callback
auth.oauth.providers.google.client-id=${GOOGLE_CLIENT_ID}
auth.oauth.providers.google.client-secret=${GOOGLE_CLIENT_SECRET}
auth.oauth.providers.github.client-id=YOUR_GITHUB_CLIENT_ID
auth.oauth.providers.github.client-secret=YOUR_GITHUB_CLIENT_SECRET

# Auth - JWT (generate real RSA keys for production)
auth.jwt.issuer=wms
auth.jwt.ttl=PT24H
auth.jwt.private-key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDXe90MCU1RIizas8MOWYFFMHJKVeF0gr/keMaV6sZ7NjOdC1FAgqouSw+EhkyzmeK7CoP7ZKWdOvEDBiO7V2AaPPGlYWSfHc5zcLH+tyUsKGTCDDFvxcraRHYm0t7x12czx+IeVCjqIuLPFDpRLEdNvpe9S/JlJBqlfeQsEozvp3T/lSYCJQysxOcFNHCGzrSzElr1wlUTcJr6aQEL5iuo8B0ueJjrPK6DdOKDQ4GyFuEKFXKxnPAZw+O2lIRyNc2z/BFW+r/TkQP93B75hOh69uoX5rsaiDvW16XVPRPPdWFpga5vI7+LLy48ITZ1p9Rca+RAsZR302w9oWP3MafBAgMBAAECggEAbbWzoogt5EwJGESD4A90AJ0c43n8MszLFHDlcri420yKVL/JW5XrPWyb9vZFoP+Nb3t4HQtuQrIauVZr5Nsko9c5lOEUUOrlDONozG3EsEnUmvOITAchM6W9niCov+rSsYtoNdbVife/EH2U/3USzKNoMEm1nQcXxgBlpoa/WNgzOO7M61SE6UW+/x4i7A5CAc2L88EgQv+H8LZeELMPH7hPLszm6YFPFzuqg9rQjNjkzW77r4lnKGXks2hH+3JnSm8B62FQ2mWZiELYJc2BZPVgrDTgz4VILZGSlOEhqDbsSjFPzGeFFYcaVuQo1ZfoQ6q9L3QnNKNEzDHqH6cVnQKBgQDxe8BCL/0sL2f09V3TdSwgny5Qk+tEf27WvXc11XCE7eHZXgxKScrxhSHAIu7s4aLRXHnLxmTqWdYydqAgbSzlZk7y14VHWLFdKLo3JPvAilsBFzyyEn4UUTutkV/HVibzJFjr5T9f1fghlubVxCVIAkY78RHkVKsdxI/HXBYBVwKBgQDkb/+n++mXe26qmIyVbQSTWyV6o+e+feWl8jbkTOxH7x3FcZP7iXtucNe2dFRVKvmPpCBzOhTLODqfDIcWvTosR+Oa0OnRiqrWIg8ovXu6Yl4DZfjYMciezbUSfjjHTc7UZQR4YX7IJl0sgCrQFL6tQQczI5Eus0zQwHoFXbp4pwKBgBEjMirAUxxOpPcKbsUx/Ja4FUZcqQascIZG3e3xHtIgO7X8aazf/coUI6gKEqC3BqILCQ3AH6tOAtiD+Ks0dEo3b4TmbKv6jGPLHyQIuOEaMIksR/9vNolklnKj7YMtBwicXL8o/s1jVv+zQOCM0gSBPNDGM/nbVGWBbJ6+V0VzAoGBANrJKeKJs0ASR/u7/2ld8HPxaAP914bqrXgyc8BUrDh5G9pu3XycQEuWaAOnht3LOxoH58x0ZFX+lKagKQHuWjju4V71l/vJA7XzCPHMCSSJ8eDvWVY22B7AhhwgJ+E69E0YMx/YwMSRecuVNWv1cmodTff8qKBBueB1eGiLTH0hAoGBAO246esU6bIXDKM2MaNjsaZhFoTZD7mamYu5RD/J/UBcWB7OOL23p+IAdQW2NILU+Qkg0WLPQfCsqOETvxEA+9H20MwLYit9qOpf7+DidZdw+igTgARxJjunloQwlYuXbKpkh9NckSztt9XgXnjiGTUTzyRHjxui+BewwFgnHWBJ
auth.jwt.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA13vdDAlNUSIs2rPDDlmBRTBySlXhdIK/5HjGlerGezYznQtRQIKqLksPhIZMs5niuwqD+2SlnTrxAwYju1dgGjzxpWFknx3Oc3Cx/rclLChkwgwxb8XK2kR2JtLe8ddnM8fiHlQo6iLizxQ6USxHTb6XvUvyZSQapX3kLBKM76d0/5UmAiUMrMTnBTRwhs60sxJa9cJVE3Ca+mkBC+YrqPAdLniY6zyug3Tig0OBshbhChVysZzwGcPjtpSEcjXNs/wRVvq/05ED/dwe+YToevbqF+a7Gog71tel1T0Tz3VhaYGubyO/iy8uPCE2dafUXGvkQLGUd9NsPaFj9zGnwQIDAQAB
